### ISSUE TITLE
Photographs

### ISSUE THREAD

**Issue by zachgharst** [pkiuna/Web-Development-2--Simply-CDL#11]

**Comment by Bobbyjuba** [comment]
I used a sample image of semi-trucks for the about page. It appears we are uses the TLS images on the homepage for SimplyCDL, no doubt as placeholders. So I think sample images like we have used so far are fine. I won't close this issue in case anyone has any additional comments.

**Comment by zachgharst** [comment]
Yes, they're placeholders for sure! I'm worried that if we show them to him, he'll want to keep them though lol
